# .rubocop.yml
require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

# Enable Rails Cops
Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

RSpec/ExampleLength:
  Max: 8

RSpec/MultipleMemoizedHelpers:
  Max: 10
