development:
  secret_key_base: <your_development_secret_key_here>

test:
  secret_key_base: <your_test_secret_key_here>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  database_name: <%= ENV["DATABASE_NAME"] %>
  database_user: <%= ENV["DATABASE_USER"] %>
  database_password: <%= ENV["DATABASE_PASSWORD"] %>
  database_host: <%= ENV["DATABASE_HOST"] %>
  database_port: <%= ENV["DATABASE_PORT"] %>
